var quick_matchMG = {
    "TPM4":"TPM4",
    "TP53BP1":"TP53BP1",
    "RIF1":"RIF1",
    "PAXIP1":"PAXIP1",
    "SOX17":"SOX17",
    "WNT5A":"WNT5A",
    "PPM1D":"PPM1D",
    "ACVR1":"ACVR1", //  24/5
    "ABL1":"ABL1",
    "ADD1":"ADD1",
    "AKT1":"AKT1",
    "ALK":"ALK",
    "ALOX12B":"ALOX12B",
    "APC":"APC",
    "AR":"AR",
    "ARID1A":"ARID1A",
    "ATM":"ATM",
    "B2M":"B2M",
    "BCAT1":"BCAT1",
    "BCL2L11":"BCL2L11",
    "BRAF":"BRAF",
    "BRCA1":"BRCA1",
    "BRCA2":"BRCA2",
    "BTK":"BTK",
    "CASP8":"CASP8",
    "CCND1":"CCND1",
    "CCND7":"CCND7",
    "CCNE1":"CCNE1",
    "CDK12":"CDK12",
    "CDK17":"CDK17",
    "CDK4":"CDK4",
    "CDK6":"CDK6",
    "CDKN1B":"CDKN1B",
    "CDKN2A":"CDKN2A",
    "CDKN2B":"CDKN2B",
    "CHD4":"CHD4",
    "C-KIT":"C-KIT",
    "CTNNB1":"CTNNB1",
    "CYP2D6":"CYP2D6",
    "DDR2":"DDR2",
    "DPH3":"DPH3",
    "EGFR":"EGFR",
    "EHBP1":"EHBP1",
    "EML4":"EML4",
    "ERBB2":"ERBB2",
    "ERBB3":"ERBB3",
    "ERBB4":"ERBB4",
    "ERG":"ERG",
    "ERRFI1":"ERRFI1",
    "ERα":"ERα",
    "ESR1":"ESR1",
    "EWSR1":"EWSR1",
    "EYA4":"EYA4",
    "EZH2":"EZH2",
    "FBXW7":"FBXW7",
    "FCGR3A":"FCGR3A",
    "FGFR1":"FGFR1",
    "FGFR2":"FGFR2",
    "FGFR3":"FGFR3",
    "FOXA1":"FOXA1",
    "FOXL2":"FOXL2",
    "GNA11":"GNA11",
    "GNAQ":"GNAQ",
    "GRIA4":"GRIA4",
    "GSTP1":"GSTP1",
    "H3":"H3",
    "H3F3A":"H3F3A",
    "HCK":"HCK",
    "HER2":"HER2",
    "HNF1A":"HNF1A",
    "HOXA9":"HOXA9",
    "HPCAL1":"HPCAL1",
    "HRAS":"HRAS",
    "HSP90AA1":"HSP90AA1",
    "IDH1":"IDH1",
    "IDH2":"IDH2",
    "IGF1R":"IGF1R",
    "IKZF1":"IKZF1",
    "ITGA3":"ITGA3",
    "ITPKB":"ITPKB",
    "JAK1":"JAK1",
    "JAK2":"JAK2",
    "JAK3":"JAK3",
    "KDR":"KDR",
    "KIF5B":"KIF5B",
    "KIT":"KIT",
    "KMT2C":"KMT2C",
    "KMT2D":"KMT2D",
    "KRAS":"KRAS",
    "MAP14K1-AS9":"MAP14K1-AS9",
    "MAP2K1":"MAP2K1",
    "MATN2":"MATN2",
    "MCL1":"MCL1",
    "MEK1":"MEK1",
    "MET":"MET",
    "MLH1":"MLH1",
    "MSC":"MSC",
    "mSEPT9":"mSEPT9",
    "mTOR":"mTOR",
    "MTRR":"MTRR",
    "MUC16":"MUC16",
    "MYC":"MYC",
    "MYCN":"MYCN",
    "MYD88":"MYD88",
    "MYH9":"MYH9",
    "NCOA1":"NCOA1",
    "NCOA2":"NCOA2",
    "NF1":"NF1",
    "NFE2L2":"NFE2L2",
    "NFKBIA":"NFKBIA",
    "NFKBIE":"NFKBIE",
    "NPTX2":"NPTX2",
    "NPY":"NPY",
    "NRAS":"NRAS",
    "NTRK":"NTRK",
    "NTRK1":"NTRK1",
    "NTRK3":"NTRK3",
    "P16":"P16",
    "PALB2":"PALB2",
    "PAX3":"PAX3",
    "PBRM1":"PBRM1",
    "PBX1":"PBX1",
    "PCLO":"PCLO",
    "PIK3CA":"PIK3CA",
    "PIK3R1":"PIK3R1",
    "PPP2R1A":"PPP2R1A",
    "PREX2":"PREX2",
    "PTCH1":"PTCH1",
    "PTEN":"PTEN",
    "PTPN11":"PTPN11",
    "RAC1":"RAC1",
    "RAD51D":"RAD51D",
    "RAF1":"RAF1",
    "RASSF1a":"RASSF1a",
    "RB1":"RB1",
    "RET":"RET",
    "RHOA":"RHOA",
    "ROS1":"ROS1",
    "RSPO":"RSPO",
    "SDHA":"SDHA",
    "SEPT9":"SEPT9",
    "SETD2":"SETD2",
    "SMAD4":"SMAD4",
    "SMARCB1":"SMARCB1",
    "SRC":"SRC",
    "STRN":"STRN",
    "TACC3":"TACC3",
    "TERT":"TERT",
    "TGFBR2":"TGFBR2",
    "TMPRSS2":"TMPRSS2",
    "TP53":"TP53",
    "TPM3":"TPM3",
    "TSC2":"TSC2",
    "U2AF1":"U2AF1",
    "WIF1":"WIF1",
    "XRCC1":"XRCC1",
    "ZNF880":"ZNF880"
}

var quick_matchMD = {
    "Metastatic Adult Medulloblastoma":"Metastatic Adult Medulloblastoma",
    "Pancreatic Neuroendocrine Neoplasms":"Pancreatic Neuroendocrine Neoplasms",
    "Hepatoblastoma":"Hepatoblastoma",
    "Diffuse Intrinsic Pontine Glioma":"Diffuse Intrinsic Pontine Glioma", //  24/5
    "Acute Myeloid Leukemia":"Acute Myeloid Leukemia",
    "Adenoid Cystic Carcinoma":"Adenoid Cystic Carcinoma",
    "Adult Granulosa Cell Tumors":"Adult Granulosa Cell Tumors",
    "Advanced Gastric Cancer":"Advanced Gastric Cancer",
    "Advanced Melanoma":"Advanced Melanoma",
    "ALK-Positive Lung Cancer":"ALK-Positive Lung Cancer",
    "Angioimmunoblastic T Cell Lymphomas":"Angioimmunoblastic T Cell Lymphomas",
    "Bladder Urothelial Carcinoma":"Bladder Urothelial Carcinoma",
    "Breast Cancer":"Breast Cancer",
    "Carcinoma Of Unknown Primary":"Carcinoma Of Unknown Primary",
    "Castration-Resistant Prostate Cancer":"Castration-Resistant Prostate Cancer",
    "Central Nervous System Lymphoma":"Central Nervous System Lymphoma",
    "Cervical Cancer":"Cervical Cancer",
    "Cholangiocarcinoma":"Cholangiocarcinoma",
    "Classical Hodgkin Lymphoma":"Classical Hodgkin Lymphoma",
    "Colon Cancer":"Colon Cancer",
    "Colorectal Cancer":"Colorectal Cancer",
    "Diffuse Glioma":"Diffuse Glioma",
    "Diffuse Large B-Cell Lymphoma":"Diffuse Large B-Cell Lymphoma",
    "Diffuse Midline Glioma":"Diffuse Midline Glioma",
    "Epithelial Ovarian Cancer":"Epithelial Ovarian Cancer",
    "Estrogen Receptor-Positive Breast Cancer":"Estrogen Receptor-Positive Breast Cancer",
    "Ewing Sarcoma":"Ewing Sarcoma",
    "Gastric Cancer":"Gastric Cancer",
    "Gastroesophageal Adenocarcinoma":"Gastroesophageal Adenocarcinoma",
    "Gastroesophageal Cancer":"Gastroesophageal Cancer",
    "Gastrointestinal Stromal Tumor":"Gastrointestinal Stromal Tumor",
    "Glioblastoma":"Glioblastoma",
    "Gliomas":"Gliomas",
    "Hepatocellular Carcinoma":"Hepatocellular Carcinoma",
    "Hepatocellular Carcinomas":"Hepatocellular Carcinomas",
    "High-Grade Colorectal Neuroendocrine Tumors":"High-Grade Colorectal Neuroendocrine Tumors",
    "High-Grade Glioma":"High-Grade Glioma",
    "Hypopharyngeal Squamous Cell Carcinoma":"Hypopharyngeal Squamous Cell Carcinoma",
    "Intrahepatic Cholangiocarcinoma":"Intrahepatic Cholangiocarcinoma",
    "Leiomyosarcoma":"Leiomyosarcoma",
    "Liver Cancer":"Liver Cancer",
    "Luminal B Breast Cancer":"Luminal B Breast Cancer",
    "Lung Adenocarcinoma":"Lung Adenocarcinoma",
    "Lung Cancer":"Lung Cancer",
    "Lung Papillary Cancer":"Lung Papillary Cancer",
    "Lung Squamous Cell Carcinoma":"Lung Squamous Cell Carcinoma",
    "Melanoma":"Melanoma",
    "Mesonephric Carcinoma":"Mesonephric Carcinoma",
    "Metastatic Ampullary Adenocarcinoma":"Metastatic Ampullary Adenocarcinoma",
    "Metastatic Bladder Cancer":"Metastatic Bladder Cancer",
    "Metastatic Breast Cancer":"Metastatic Breast Cancer",
    "Metastatic Castration-Resistant Prostate Cancer":"Metastatic Castration-Resistant Prostate Cancer",
    "Metastatic Colorectal Cancer":"Metastatic Colorectal Cancer",
    "Metastatic Esophageal Cancer":"Metastatic Esophageal Cancer",
    "Metastatic Melanoma":"Metastatic Melanoma",
    "Metastatic Pancreatic Adenocarcinoma":"Metastatic Pancreatic Adenocarcinoma",
    "Metastatic Pancreatic Cancer":"Metastatic Pancreatic Cancer",
    "Metastatic Urothelial Carcinoma":"Metastatic Urothelial Carcinoma",
    "Mismatch Repair–Deficient Cancers":"Mismatch Repair–Deficient Cancers",
    "Multiple Myeloma":"Multiple Myeloma",
    "Muscle-Invasive Bladder Cancer":"Muscle-Invasive Bladder Cancer",
    "Myelofibrosis":"Myelofibrosis",
    "Myxoid Liposarcomas":"Myxoid Liposarcomas",
    "Neuroblastoma":"Neuroblastoma",
    "Non-Small Cell Lung Cancer":"Non-Small Cell Lung Cancer",
    "Oropharyngeal Squamous Cell Carcinoma":"Oropharyngeal Squamous Cell Carcinoma",
    "Ovarian Cancer":"Ovarian Cancer",
    "Pancreatic Cancer":"Pancreatic Cancer",
    "Pancreatic Ductal Adenocarcinoma":"Pancreatic Ductal Adenocarcinoma",
    "Pancreatic obiliary Adenocarcinoma":"Pancreatic obiliary Adenocarcinoma",
    "Papillary Thyroid Carcinoma":"Papillary Thyroid Carcinoma",
    "Pediatric High-Grade Glioma":"Pediatric High-Grade Glioma",
    "Pediatric Sarcomas":"Pediatric Sarcomas",
    "Prostate Adenocarcinoma":"Prostate Adenocarcinoma",
    "Prostate Cancer":"Prostate Cancer",
    "Rectal Cancer":"Rectal Cancer",
    "Small Cell Carcinoma Of The Prostate":"Small Cell Carcinoma Of The Prostate",
    "Small Cell Lung Cancer":"Small Cell Lung Cancer",
    "Spinal Myxopapillary Ependymoma":"Spinal Myxopapillary Ependymoma",
    "Squamous Cell Carcinoma Of The Anal Canal":"Squamous Cell Carcinoma Of The Anal Canal",
    "Thyroid Nodules":"Thyroid Nodules",
    "Triple Negative Breast Cancer":"Triple Negative Breast Cancer",
    "Urothelial Carcinoma":"Urothelial Carcinoma",
    "Uveal Melanoma":"Uveal Melanoma"
}

var quick_mathGG = {
    "MSH2":"MSH2",
    "MSH6":"MSH6",
    "PMS2":"PMS2",
    "AMER1":"AMER1",
    "IGLL5":"IGLL5",
    "DIS3":"DIS3",
    "PBRM1 ":"PBRM1 ",
    "SMAD4":"SMAD4",
    "CREBBP":"CREBBP",
    "RAF":"RAF",
    "SPEN":"SPEN",
    "BCOR":"BCOR",
    "IKBKB":"IKBKB",
    "NOTCH2":"NOTCH2",
    "TGFBR2":"TGFBR2",
    "RHOA":"RHOA",
    "FAT4":"FAT4",
    "E7":"E7",
    "BCL2L1":"BCL2L1",
    "RAD50":"RAD50", // 24/5
    "ZNF217":"ZNF217",
    "ABL1":"ABL1",
    "ALK":"ALK",
    "ANO1":"ANO1",
    "AP3B1":"AP3B1",
    "APC":"APC",
    "AR":"AR",
    "ARAF":"ARAF",
    "ARID1A":"ARID1A",
    "ATM":"ATM",
    "B2M":"B2M",
    "BCL6":"BCL6",
    "BCL7A":"BCL7A",
    "BRAF":"BRAF",
    "BRCA":"BRCA",
    "BRCA1":"BRCA1",
    "BRCA2":"BRCA2",
    "BTG2":"BTG2",
    "CBLB":"CBLB",
    "CCND2":"CCND2",
    "CCNE1":"CCNE1",
    "CDH1":"CDH1",
    "CDK12":"CDK12",
    "CDK4":"CDK4",
    "CDKN2A":"CDKN2A",
    "CDKN2B":"CDKN2B",
    "CDKN2C":"CDKN2C",
    "CEBPA":"CEBPA",
    "CTCF":"CTCF",
    "CTNNB1":"CTNNB1",
    "DNMT3A":"DNMT3A",
    "EGFR":"EGFR",
    "EPCAM":"EPCAM",
    "ERBB2":"ERBB2",
    "ESR1":"ESR1",
    "EWSR1":"EWSR1",
    "FAT3":"FAT3",
    "FBXO11":"FBXO11",
    "FBXW7":"FBXW7",
    "FGF23":"FGF23",
    "FGFR2":"FGFR2",
    "FGFR3":"FGFR3",
    "FGFR4":"FGFR4",
    "FRS2":"FRS2",
    "FUBP1":"FUBP1",
    "GATA3":"GATA3",
    "GNA11":"GNA11",
    "GNAQ":"GNAQ",
    "GNAS":"GNAS",
    "H3F3A":"H3F3A",
    "H3F3C":"H3F3C",
    "H3K27M":"H3K27M",
    "HER2":"HER2",
    "HLA-E":"HLA-E",
    "HTERT":"HTERT",
    "IGF1R":"IGF1R",
    "JAK1":"JAK1",
    "JAK2":"JAK2",
    "KDM2B":"KDM2B",
    "KEAP1":"KEAP1",
    "KIT":"KIT",
    "KMT2B":"KMT2B",
    "KMT2D":"KMT2D",
    "KRAS":"KRAS",
    "LAG3":"LAG3",
    "LRP1B":"LRP1B",
    "LRP6":"LRP6",
    "MAP2K1":"MAP2K1",
    "MDM2":"MDM2",
    "MEF2B":"MEF2B",
    "MET":"MET",
    "MIKI67":"MIKI67",
    "MITF":"MITF",
    "MLH1":"MLH1",
    "MLL":"MLL",
    "MLL2":"MLL2",
    "MLL3":"MLL3",
    "MUC16":"MUC16",
    "MYC":"MYC",
    "NARS":"NARS",
    "NF1":"NF1",
    "NOTCH1":"NOTCH1",
    "NRAS":"NRAS",
    "PCLO":"PCLO",
    "PDGFRA":"PDGFRA",
    "PI3KCA":"PI3KCA",
    "PIK3CA":"PIK3CA",
    "PIK53CA":"PIK53CA",
    "PREX2":"PREX2",
    "PTEN":"PTEN",
    "RAS":"RAS",
    "RB1":"RB1",
    "RICTOR":"RICTOR",
    "RNF213":"RNF213",
    "ROS1":"ROS1",
    "S19R":"S19R",
    "SESN1":"SESN1",
    "SFRP1":"SFRP1",
    "SMARCA4":"SMARCA4",
    "SNHG16":"SNHG16",
    "SOCS1":"SOCS1",
    "STAT5B":"STAT5B",
    "STAT6":"STAT6",
    "STK11":"STK11",
    "TCF7L2":"TCF7L2",
    "TERT":"TERT",
    "TET2":"TET2",
    "THSD7B":"THSD7B",
    "TNFAIP3":"TNFAIP3",
    "TNFRSF14":"TNFRSF14",
    "TOP2A":"TOP2A",
    "TP53":"TP53",
    "TSC1":"TSC1",
    "TSC2":"TSC2",
    "TTN":"TTN",
    "VHL":"VHL"
}

var quick_matchGD = {
    "Gliomas":"Gliomas",
    "Small Cell Lung Cancer":"Small Cell Lung Cancer",
    "Relapsed Or Refractory Large B-Cell Lymphoma":"Relapsed Or Refractory Large B-Cell Lymphoma",
    "Relapsed Or Refractory Multiple Myeloma":"Relapsed Or Refractory Multiple Myeloma",
    "Locally Advanced Cervical Cancers":"Locally Advanced Cervical Cancers",
    "Metastatic Esophageal Squamous Cell Carcinoma":"Metastatic Esophageal Squamous Cell Carcinoma",
    "Follicular Lymphoma":"Follicular Lymphoma",
    "Hepatoblastoma":"Hepatoblastoma", // 24/5
    "Advanced Or Recurrent Endometrial Carcinoma":"Advanced Or Recurrent Endometrial Carcinoma",
    "Alveolar Soft Part Sarcoma":"Alveolar Soft Part Sarcoma",
    "Anal Squamous Cell Carcinoma":"Anal Squamous Cell Carcinoma",
    "Breast Cancer":"Breast Cancer",
    "Castrate Resistant Prostate Cancer":"Castrate Resistant Prostate Cancer",
    "Cervical Cancers":"Cervical Cancers",
    "Classical Hodgkin Lymphoma":"Classical Hodgkin Lymphoma",
    "Clear Cell Renal Cell Carcinoma":"Clear Cell Renal Cell Carcinoma",
    "Colorectal Cancer":"Colorectal Cancer",
    "De-Differentiated Liposarcoma":"De-Differentiated Liposarcoma",
    "Diffuse Intrinsic Pontine Glioma":"Diffuse Intrinsic Pontine Glioma",
    "Diffuse Large B-Cell Lymphoma":"Diffuse Large B-Cell Lymphoma",
    "Diffuse Midline Glioma":"Diffuse Midline Glioma",
    "Endometrial Cancer":"Endometrial Cancer",
    "Epithelial Ovarian Cancer":"Epithelial Ovarian Cancer",
    "Ewing Sarcoma":"Ewing Sarcoma",
    "Gastric Cancer":"Gastric Cancer",
    "Gastroenteropancreatic Neuroendocrine Carcinomas":"Gastroenteropancreatic Neuroendocrine Carcinomas",
    "Gastrointestinal Stromal Tumor":"Gastrointestinal Stromal Tumor",
    "Hepatocellular Carcinoma":"Hepatocellular Carcinoma",
    "High-Grade Ovarian Carcinoma":"High-Grade Ovarian Carcinoma",
    "High-Grade Serous Ovarian Carcinoma":"High-Grade Serous Ovarian Carcinoma",
    "Hodgkin Lymphoma":"Hodgkin Lymphoma",
    "Intrahepatic Cholangiocarcinoma":"Intrahepatic Cholangiocarcinoma",
    "Invasive Lobular Carcinoma":"Invasive Lobular Carcinoma",
    "Liver Cancer":"Liver Cancer",
    "Lung Adenocarcinoma":"Lung Adenocarcinoma",
    "Lung Cancer":"Lung Cancer",
    "Lymphoma":"Lymphoma",
    "Melanoma":"Melanoma",
    "Metastatic Breast Cancer":"Metastatic Breast Cancer",
    "Metastatic Castration-Resistant Prostate Cancer":"Metastatic Castration-Resistant Prostate Cancer",
    "Metastatic Colorectal Cancer":"Metastatic Colorectal Cancer",
    "Metastatic Melanoma":"Metastatic Melanoma",
    "Metastatic Urothelial Cancer":"Metastatic Urothelial Cancer",
    "Multiple Myeloma":"Multiple Myeloma",
    "Neuroblastoma":"Neuroblastoma",
    "Non-Small Cell Lung Cancer":"Non-Small Cell Lung Cancer",
    "Ovarian Cancer":"Ovarian Cancer",
    "Pancreatic Adenocarcinoma":"Pancreatic Adenocarcinoma",
    "Pancreatic Cancer":"Pancreatic Cancer",
    "Pancreatic Ductal Adenocarcinoma":"Pancreatic Ductal Adenocarcinoma",
    "Prostate Cancer":"Prostate Cancer",
    "Pulmonary Lymphangioleiomyomatosis":"Pulmonary Lymphangioleiomyomatosis",
    "Squamous Cell Carcinoma Of The Head And Neck":"Squamous Cell Carcinoma Of The Head And Neck",
    "T-Cell Lymphoma":"T-Cell Lymphoma",
    "Triple Negative Breast Cancer":"Triple Negative Breast Cancer",
    "Upper Tract Urothelial Carcinoma":"Upper Tract Urothelial Carcinoma",
    "Urothelial Cancer":"Urothelial Cancer",
    "Uveal Melanoma":"Uveal Melanoma"
}

$(function () {
    'use strict';

    var GGArray = $.map(quick_mathGG, function (value, key) { return { value: value, data: key }; });
    var GDArray = $.map(quick_matchGD, function (value, key) { return { value: value, data: key }; });
    var MGArray = $.map(quick_matchMG, function (value, key) { return { value: value, data: key }; });
    var MDArray = $.map(quick_matchMD, function (value, key) { return { value: value, data: key }; });
    $('#g_gene_quick').autocomplete({
        // serviceUrl: '/autosuggest/service/url',
        lookup: GGArray,
        lookupFilter: function(suggestion, originalQuery, queryLowerCase) {
            var re = new RegExp('\\b' + $.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
            return re.test(suggestion.value);
        },
        onSelect: function(suggestion) {
            $('#selction-ajax').html('You selected: ' + suggestion.value + ', ' + suggestion.data);
        },
        onHint: function (hint) {
            $('#autocomplete-ajax-x').val(hint);
        },
        onInvalidateSelection: function() {
            $('#selction-ajax').html('You selected: none');
        }
    });

    $('#g_disease_quick').autocomplete({
        // serviceUrl: '/autosuggest/service/url',
        lookup: GDArray,
        lookupFilter: function(suggestion, originalQuery, queryLowerCase) {
            var re = new RegExp('\\b' + $.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
            return re.test(suggestion.value);
        },
        onSelect: function(suggestion) {
            $('#selction-ajax').html('You selected: ' + suggestion.value + ', ' + suggestion.data);
        },
        onHint: function (hint) {
            $('#autocomplete-ajax-x').val(hint);
        },
        onInvalidateSelection: function() {
            $('#selction-ajax').html('You selected: none');
        }
    });

    $('#m_disease_quick').autocomplete({
        // serviceUrl: '/autosuggest/service/url',
        lookup: MDArray,
        lookupFilter: function(suggestion, originalQuery, queryLowerCase) {
            var re = new RegExp('\\b' + $.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
            return re.test(suggestion.value);
        },
        onSelect: function(suggestion) {
            $('#selction-ajax').html('You selected: ' + suggestion.value + ', ' + suggestion.data);
        },
        onHint: function (hint) {
            $('#autocomplete-ajax-x').val(hint);
        },
        onInvalidateSelection: function() {
            $('#selction-ajax').html('You selected: none');
        }
    });

    $('#m_gene_quick').autocomplete({
        // serviceUrl: '/autosuggest/service/url',
        lookup: MGArray,
        lookupFilter: function(suggestion, originalQuery, queryLowerCase) {
            var re = new RegExp('\\b' + $.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
            return re.test(suggestion.value);
        },
        onSelect: function(suggestion) {
            $('#selction-ajax').html('You selected: ' + suggestion.value + ', ' + suggestion.data);
        },
        onHint: function (hint) {
            $('#autocomplete-ajax-x').val(hint);
        },
        onInvalidateSelection: function() {
            $('#selction-ajax').html('You selected: none');
        }
    });
})